### ISSUE TITLE
Error: type UpdateResults does not take parameters

### ISSUE THREAD

**Issue by ccaspanello** [evanchooly/critter#3]
I've pulled in your Entity classes into a new project; included the 2 dependencies.  The classes get generated; however, there are compilation errors:

InvoiceCriteria.java:[66,50] error: type UpdateResults does not take parameters.

Any help with this would be awesome.

Thanks,
Chris

**Comment by evanchooly** [comment]
Just pushed 2.0.0 last night which fixes this.

**Comment by ccaspanello** [comment]
Awesome, thanks!  I'll give this a shot.
